---
version: '3.9'

services:
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    env_file:
        - ./.env
    volumes:
      - ./redis-data:/data
    restart: unless-stopped

  mongo:
    image: "mongo"
    ports:
      - "27017:27017"
    env_file:
        - ./.env
    volumes:
      - ./db-data/:/data
    restart: unless-stopped

  aurene:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - redis
      - mongo
    ports:
      - "3000:3000"
    env_file:
      - ./.env
    volumes:
      - ./:/app
      - /app/node_modules
    restart: on-failure
